"""Módulo principal del compilador RIF.

Expone la interfaz pública para el Lexer, Parser, Linker, Packer, Compiler
y los modelos de datos esenciales que estructuran el flujo del framework.
"""

__version__ = "0.0.1b1"

from .errors import RIFError, LexError, ParseError, PackError, Errors, EndSignal, end
from .lexer import Lexer
from .parser import Parser, collect_codegen
from .linker import Linker, link_file, build_file, build_project
from .packer import Packer, build_pack, pack_file
from .resolver import PlaceholderResolver, resolve_placeholders
from .compiler import Compiler, compile_instruction
from .source_reader import SourceEntry, SourceReader, SourceReadResult
from .models import (
    Token,
    Program,
    BitVariable,
    DataDefinitionInfo,
    HeaderBlock,
    HeadersInfo,
    Section,
    Statement,
    MemoryInfo,
    MemoryRegion,
    PackerConfig,
    PackedResult,
    LinkBlock,
    BinaryLinkResult,
    TYPES_MAP,
    TypeInfo,
    Line,
    Err,
    Expr,
    IDENT,
    Operators,
    Operator,
    RuleIndicator,
    TypeDefinition,
    TypesInfo,
    OperatorBinding,
    REG,
    DATA,
    EmitChunk,
    EmitInstruction,
    FlowInstruction,
    CodegenInfo,
    Placeholder,
    PluginContext,
    PlaceholderResolution,
    Relocation,
    ResolvedPlaceholder,
    OperandValue,
    CompileResult,
)

__all__ = [
    "__version__",
    "RIFError",
    "LexError",
    "ParseError",
    "PackError",
    "Errors",
    "EndSignal",
    "end",
    "Lexer",
    "Parser",
    "collect_codegen",
    "Linker",
    "link_file",
    "build_file",
    "build_project",
    "Packer",
    "build_pack",
    "pack_file",
    "PlaceholderResolver",
    "resolve_placeholders",
    "Compiler",
    "compile_instruction",
    "Token",
    "Program",
    "BitVariable",
    "DataDefinitionInfo",
    "HeaderBlock",
    "HeadersInfo",
    "Section",
    "Statement",
    "MemoryInfo",
    "MemoryRegion",
    "PackerConfig",
    "PackedResult",
    "LinkBlock",
    "BinaryLinkResult",
    "TYPES_MAP",
    "TypeInfo",
    "Line",
    "Err",
    "Expr",
    "IDENT",
    "Operators",
    "Operator",
    "RuleIndicator",
    "TypeDefinition",
    "TypesInfo",
    "OperatorBinding",
    "REG",
    "DATA",
    "EmitChunk",
    "EmitInstruction",
    "FlowInstruction",
    "CodegenInfo",
    "Placeholder",
    "PluginContext",
    "PlaceholderResolution",
    "Relocation",
    "ResolvedPlaceholder",
    "OperandValue",
    "CompileResult",
    "SourceEntry",
    "SourceReader",
    "SourceReadResult",
]
